### PR TITLE
feat: add version check to CI via VERSION file

### PR DESCRIPTION
**Pull request by J0**
## What kind of change does this PR introduce?

PR for semver release workflow derived from the PR in #76  . Based on discussion it sounds like we  want either:

- Logflare has [a VERSION file](https://github.com/Logflare/logflare/blob/staging/VERSION) we do things with.
- Realtime has a [mix version check](https://github.com/supabase/realtime/blob/main/.github/workflows/version_updated.yml) so it reminds us to update the version there too.
- Something else

Left as draft for now, can decide what to do in the coming week.

### CODE REVIEW

**Comment by J0** [comment]
Hey @chasers, @abc3,

Just wanted to circle back and check in on this - any preference between:

1. Logflare has [a VERSION file](https://github.com/Logflare/logflare/blob/staging/VERSION) we do things with.

2. Realtime has a [mix version check](https://github.com/supabase/realtime/blob/main/.github/workflows/version_updated.yml) so it reminds us to update the version there too.

3. Other

Was hoping to close this out before I return from OOO on Wed evening PST.  Can also close this for now if more discussion is needed.

Let me know!

**Comment by chasers** [comment]
@J0 let's do the VERSION file like Logflare. And how we pull in the version from that into the mix.exs file.

**Comment by J0** [comment]
Hey @chasers,

Not sure if this is what you had in mind - this imposes a check which requires the dev to manually update the `VERSION` file for the PR similar to [how it is done in realtime](https://github.com/supabase/realtime/blob/main/.github/workflows/version_updated.yml#L24)

Let me know if you had something else in mind and I can adjust accordingly.

**Comment by chasers** [comment]
Thanks so much! LGTM!

**Review by chasers — APPROVED** [review]

**Pull request merged**
