### PR TITLE
chore: add eFlambe

### PR DESCRIPTION
**Pull request by hauleth**
## What kind of change does this PR introduce?

Add eFlambé to the development tools to help with profiling code in development.

### CODE REVIEW

**Review by abc3 — APPROVED** [review]

**Comment by abc3** [comment]
🔥 🔥 🔥

**Comment by abc3** [comment]
JFYI @filipecabaco

**Comment by hauleth** [comment]
eFlambe and Speedoscope are GOATs

**Comment by hauleth** [comment]
@abc3 can we rerun test suite? I cannot do it on my own.

**Comment by abc3** [comment]
triggered

**Pull request merged**
