### PR TITLE
feat: reset the check timer after the client's disconnection

### PR DESCRIPTION
**Pull request by abc3**
This PR resets the check_subscribers timer after each disconnection

### CODE REVIEW

**Comment by josevalim** [comment]
@abc3 can you expand it a bit more on what you are seeing? Could you rather have concurrent updates on the table? If concurrent updates are not expected, what about setting the table as `:protected`, to guarantee you are not running into concurrency issues?

**Comment by abc3** [comment]
@josevalim, sometimes, we see that a client is trying to subscribe to a recently stopped manager. I think it's because the current check_timeout simply occurs every 2 minutes and can catch a short moment when a tenant doesn't have any subscribers, leading to the connection being closed. Ets with subscribers can only be updated from a single GenServer. I just want to be sure that the ets size always shows the actual number of records in the table

**Comment by josevalim** [comment]
If the size is read within the same process doing the writes, then it should not be out of sync, yeah. If you only write from a process, I recommend changing the table from :public to :protected. :)

**Comment by abc3** [comment]
@josevalim I'll change it to protected, thanks!

**Pull request merged**
